# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('airport_type', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('iso_country', models.TextField(blank=True, null=True)),
                ('iso_region', models.TextField(blank=True, null=True)),
                ('municipality', models.TextField(blank=True, null=True)),
                ('gps_code', models.TextField(blank=True, null=True)),
                ('iata_code', models.TextField(blank=True, null=True)),
                ('local_code', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('temperature', models.FloatField()),
                ('atmosphere_pressure', models.FloatField()),
                ('atmosphere_rising', models.FloatField()),
                ('atmosphere_visibility', models.FloatField()),
                ('atmosphere_humidity', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_chill', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Location')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
