# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-03 18:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BACNetLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('device_id', models.PositiveIntegerField(default=0)),
                ('property_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'BACNet Light',
                'verbose_name_plural': 'BACNet Lights',
            },
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('pjlink_host', models.CharField(max_length=1024)),
                ('pjlink_port', models.IntegerField(default=4352)),
                ('pjlink_password', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('days', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('hours', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('minutes', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('last_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tries', models.IntegerField(default=0, editable=False)),
                ('command', models.CharField(choices=[(b'on', b'Turn On'), (b'off', b'Turn Off')], default=b'off', max_length=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting.Projector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
