# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creston',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('host', models.CharField(max_length=1024)),
                ('port', models.IntegerField(default=1313)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
