# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0003_creston_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacnetlight',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projector',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
