# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-07 19:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0004_bacnet_projector_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrestonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('days', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('hours', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('minutes', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('last_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tries', models.IntegerField(default=0, editable=False)),
                ('command', models.CharField(choices=[(b'Ping', b'Ping'), (b'Update', b'Query system'), (b'EnableDim', b'Dim On/Off Toggle'), (b'DimLvlUp', b'To adjust the Dim sensitivity up'), (b'DimLvlDown', b'To adjust the Dim sensitivity down'), (b'EnableHigh', b'High On/Off Toggle'), (b'HighLvlUp', b'To adjust the high sensitivity brightness up'), (b'HighLvlDown', b'To adjust the high sensitivity brightness down'), (b'MemoryStore', b'To store a Dim and High memory preset level'), (b'MemoryRecall', b'To recall a Dim and High memory preset level'), (b'Display1On', b'To turn on the left projector'), (b'Display1Off', b'To turn off the left projector'), (b'Display1DVI', b'To view DVI Input on left projector'), (b'Display1HighBright', b'To adjust the image brightness of the left projector to its highest level'), (b'Display1LowBright', b'To adjust the image brightness of the left projector to its lowest level'), (b'Display2On', b'To turn on the right projector'), (b'Display2Off', b'To turn off the right projector'), (b'Display2DVI', b'To view DVI input on right projector'), (b'Display2HighBright', b'To adjust the image brightness of the right projector to its highest level'), (b'Display2LowBright', b'To adjust the image brightness of the right projector to its lowest level'), (b'WakeEnable', b'This is to set a specified time for projectors to power On/Off Toggle'), (b'WakeHrUp', b'To adjust the hour parameter up for turning on the system'), (b'WakeHrDown', b'To adjust the hour parameter down for turning on the system'), (b'WakeMinUp', b'To adjust the minute parameter up for turning on the system'), (b'WakeMinDown', b'To adjust the minute parameter down for turning on the system'), (b'SleepEnable', b'Projector power timer to set powering down of both projectors after a specified amount of time'), (b'SleepHrUp', b'To adjust the hour parameter up for the projector sleep function'), (b'SleepHrDown', b'To adjust the hour parameter down for the projector sleep function'), (b'SleepMinUp', b'To adjust the minute parameter up for the projector sleep function'), (b'SleepMinDown', b'To adjust the minute parameter down for the projector sleep function')], default=b'off', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting.Creston')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
