# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 02:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBootDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('mac_address', models.CharField(help_text=b'e.g. 00-0D-AD-01-94-6F', max_length=1024)),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'iBoot Device',
                'verbose_name_plural': 'iBoot Devices',
            },
        ),
        migrations.CreateModel(
            name='IBootEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('days', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('hours', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('minutes', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('last_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tries', models.IntegerField(default=0, editable=False)),
                ('command', models.CharField(choices=[(b'cycle', b'Cycle'), (b'on', b'Turn On'), (b'off', b'Turn Off'), (b'toggle', b'Toggle')], default=b'cycle', max_length=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iboot.IBootDevice')),
            ],
            options={
                'verbose_name': 'iBoot Event',
                'verbose_name_plural': 'iBoot Events',
            },
        ),
    ]
