# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iboot', '0002_auto_20180530_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibootdevice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
