# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iboot', '0003_ibootdevice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibootdevice',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
