# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
