# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_installation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgroup',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='artwork.Artist'),
        ),
    ]
