# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_add_blank_for_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgroup',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artwork.Artist'),
        ),
    ]
