# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('artwork', '0004_added_for_0003_kill_warning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
